[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.0"

[[override]]
  name = "github.com/Azure/go-autorest"
  version = "v10.6.2"